Repository Orbits-Inc/orbits, pull requests merged in 2021-07, with the labels that each got.

#46 Added more UI elements
  package-lock.json
  package.json
  public/Orb.svg
  public/sw.js
  public/sw.js.map
  public/workbox-6b19f60b.js
  src/components/Custom/custominput.component.tsx
  src/components/Custom/searchbar.component.tsx
  src/components/Custom/tag.component.tsx
  src/components/Misc/profilecrumb.component.tsx
  src/components/Misc/switcher.component.tsx
  src/components/PageAssets/navbar.component.tsx
  src/components/PageAssets/signin.component.tsx
  src/components/Post/comment.component.tsx
  src/components/Post/postcard.component.tsx
  src/components/Post/postcrumb.component.tsx
  src/components/Skeletons/SkeletonPost.tsx
  src/global.d.ts
  src/pages/search/[query].tsx
  src/sections/Dashboard/dashboard.section.tsx
  src/sections/Dashboard/modal.section.tsx
  src/sections/Dashboard/tabchanger.section.tsx
  src/sections/Dashboard/writepost.section.tsx
  src/sections/Post/comments.section.tsx
  src/sections/Post/posts.section.tsx
  src/sections/Post/trendingposts.section.tsx
  src/sections/SearchResults/articles.section.tsx
  src/sections/SearchResults/nothingFound.component.tsx
  src/sections/SearchResults/people.section.tsx
  src/sections/SearchResults/searching.component.tsx
  src/styles/globals.css
  src/utils/helpers/post/add_new_post.ts
  src/utils/helpers/post/get_post.ts
  src/utils/helpers/post/search_post.ts
  src/utils/helpers/user/add_new_user.ts
  src/utils/helpers/user/get_user.ts
  src/utils/helpers/user/search_user.ts
  src/utils/helpers/user/username_suggestion.ts
  src/utils/providers/api.provider.tsx
  src/utils/providers/auth.provider.tsx
  tailwind.config.js
  tsconfig.json
Labels: design update

#59 Fix: tailwind not working in prod
  src/sections/SearchResults/results.component.jsx
  tailwind.config.js
Labels: bug

#58 Signin Onboarding
  .gitignore
  .prettierrc.json
  components/Custom/InputField.tsx
  components/Custom/custombutton.component.tsx
  components/Custom/custominput.component.tsx
  components/Custom/searchbar.component.tsx
  components/Custom/tag.component.tsx
  components/PageAssets/navbar.component.tsx
  components/PageAssets/page404.component.tsx
  components/Post/postcard.component.tsx
  components/SignIn/GoBackContinueButton.tsx
  components/SignIn/SignInStages/stage1.section.tsx
  components/SignIn/SignInStages/stage2.section.tsx
  components/SignIn/SignInStages/stage3.section.tsx
  components/SignIn/firebaseSignin.component.tsx
  components/SignIn/firebaseUI.componet.tsx
  components/SignIn/progressbar.section.tsx
  components/SignIn/signInCard.component.tsx
  components/SignIn/signin.component.tsx
  components/SignIn/signin.provider.tsx
  components/SignIn/types.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/onboarding.tsx
  pages/search/[query].tsx
  public/OnboardingBackground.svg
  public/spinner.svg
  public/successfull.svg
  public/sw.js
  public/sw.js.map
  public/workbox-6b19f60b.js
  sections/Dashboard/SideBar/loginprompt.sidebar.tsx
  sections/Dashboard/SideBar/trendingposts.sidebar.tsx
  sections/Dashboard/SideBar/trendingtags.sidebar.tsx
  sections/Dashboard/modal.section.tsx
  sections/Dashboard/tabchanger.section.tsx
  sections/Dashboard/writepost.section.tsx
  sections/Post/posts.section.tsx
  styles/globals.css
  tailwind.config.js
  tsconfig.json
  utils/helpers/user/get_user.ts
  utils/topicsInterested.ts
Labels: design update, enhancement

#63 Hide "Get Started" when logged in
  sections/Dashboard/dashboard.section.tsx
  utils/providers/auth.provider.tsx
Labels: bug
