Repository Orbits-Inc/orbits, pull requests merged in 2021-06, with the labels that each got.

#24 Made Orbits PWA! 🚀
  .gitignore
  next.config.js
  package-lock.json
  package.json
  pages/_app.js
  public/manifest.json
Labels: enhancement

#29 Typescript rewrite
  components/Custom/custombutton.component.jsx
  components/Custom/custombutton.component.tsx
  components/Custom/custominput.component.tsx
  components/Custom/header.component.tsx
  components/Custom/searchbar.component.tsx
  components/Custom/tag.component.tsx
  components/Misc/mention.component.tsx
  components/Misc/navlink.component.tsx
  components/Misc/popup.component.tsx
  components/Misc/profilecrumb.component.tsx
  components/Misc/switcher.component.jsx
  components/Misc/switcher.component.tsx
  components/PageAssets/navbar.component.tsx
  components/PageAssets/page404.component.tsx
  components/PageAssets/signin.component.tsx
  components/Post/comment.component.tsx
  components/Post/postcard.component.tsx
  components/Post/postcrumb.component.tsx
  next-env.d.ts
  package-lock.json
  package.json
  pages/404.tsx
  pages/_app.js
  pages/_app.tsx
  pages/index.tsx
  pages/search/[query].tsx
  sections/Dashboard/dashboard.section.tsx
  sections/Dashboard/modal.section.tsx
  sections/Dashboard/writepost.section.tsx
  sections/Post/comments.section.tsx
  sections/Post/posts.section.tsx
  sections/Post/trendingposts.section.tsx
  sections/SearchResults/articles.section.tsx
  sections/SearchResults/people.section.tsx
  tsconfig.json
  types/data.types.ts
  types/ui.types.ts
  utils/firebase.ts
  utils/helpers/post/add_new_post.ts
  utils/helpers/post/get_post.ts
  utils/helpers/post/search_post.ts
  utils/helpers/user/add_new_user.ts
  utils/helpers/user/get_user.ts
  utils/helpers/user/search_user.ts
  utils/helpers/user/username_suggestion.ts
  utils/popular_tags.ts
  utils/providers/api.provider.js
  utils/providers/api.provider.tsx
  utils/providers/auth.provider.tsx
  utils/providers/popup.provider.tsx
Labels: enhancement

#30 Fix lint action
  .github/workflows/lint.yml
  package-lock.json
  package.json
Labels: bug

#32 Redirect to /auth for authentication
  components/Misc/branding.tsx
  components/PageAssets/navbar.component.tsx
  components/PageAssets/signin.component.tsx
  pages/_app.tsx
  pages/auth.tsx
  public/sw.js
  public/sw.js.map
  public/workbox-6b19f60b.js
Labels: bug, enhancement

#36 Added A Loading Progress Bar
  package-lock.json
  package.json
  pages/_app.tsx
  public/sw.js.map
  styles/globals.css
Labels: enhancement

#41 Create AuthRequired component
  components/Misc/authRequired.tsx
  components/PageAssets/navbar.component.tsx
  components/PageAssets/page404.component.tsx
  components/PageAssets/signin.component.tsx
  components/Post/postcard.component.tsx
  sections/Dashboard/dashboard.section.tsx
  sections/Dashboard/writepost.section.tsx
  utils/providers/api.provider.tsx
  utils/providers/auth.provider.tsx
Labels: enhancement

#43 Update switcher
  components/Misc/switcher.component.tsx
  sections/Dashboard/dashboard.section.tsx
Labels: enhancement

#45 Move everything to src/
  src/components/Custom/custombutton.component.tsx
  src/components/Custom/custominput.component.tsx
  src/components/Custom/header.component.tsx
  src/components/Custom/searchbar.component.tsx
  src/components/Custom/tag.component.tsx
  src/components/Misc/authRequired.tsx
  src/components/Misc/branding.tsx
  src/components/Misc/mention.component.tsx
  src/components/Misc/navlink.component.tsx
  src/components/Misc/popup.component.tsx
  src/components/Misc/profilecrumb.component.tsx
  src/components/Misc/switcher.component.tsx
  src/components/PageAssets/navbar.component.tsx
  src/components/PageAssets/page404.component.tsx
  src/components/PageAssets/signin.component.tsx
  src/components/Post/comment.component.tsx
  src/components/Post/postcard.component.tsx
  src/components/Post/postcrumb.component.tsx
  src/components/Skeletons/SkeletonPost.tsx
  src/pages/404.tsx
  src/pages/_app.tsx
  src/pages/api/hello.js
  src/pages/auth.tsx
  src/pages/index.tsx
  src/pages/search/[query].tsx
  src/sections/Dashboard/dashboard.section.tsx
  src/sections/Dashboard/modal.section.tsx
  src/sections/Dashboard/writepost.section.tsx
  src/sections/Post/comments.section.tsx
  src/sections/Post/posts.section.tsx
  src/sections/Post/trendingposts.section.tsx
  src/sections/SearchResults/articles.section.tsx
  src/sections/SearchResults/nothingFound.component.jsx
  src/sections/SearchResults/people.section.tsx
  src/sections/SearchResults/results.component.jsx
  src/sections/SearchResults/searching.component.jsx
  src/styles/Home.module.css
  src/styles/globals.css
  src/types/data.types.ts
  src/types/ui.types.ts
  src/utils/firebase.ts
  src/utils/helpers/post/add_new_post.ts
  src/utils/helpers/post/get_post.ts
  src/utils/helpers/post/search_post.ts
  src/utils/helpers/user/add_new_user.ts
  src/utils/helpers/user/get_user.ts
  src/utils/helpers/user/search_user.ts
  src/utils/helpers/user/username_suggestion.ts
  src/utils/popular_tags.ts
  src/utils/providers/api.provider.tsx
  src/utils/providers/auth.provider.tsx
  src/utils/providers/popup.provider.tsx
Labels: enhancement
